### ISSUE TITLE
I should be able to apply a common set of rules to N sections

### ISSUE THREAD

**Issue by sheax0r** [drewfradette/ruby-ficus#1]
As an example, suppose I want a config file that looks like this:

``` yaml
servers:
  server1: 
    username: ME
    password: SECRET
  server2:
     username: YOU
     password: ANOTHER_SECRET
```

I would like to be able to enforce that the same rules get applied to all subsections of "servers".

Maybe something like this?

``` ruby
section 'servers' do
  section :all do
    required :username
    required :password
  end
end
```
